[[dotbots]]
address = "AAAAAAAAAAAA0000"
calibrated = true
pos_x = 800000
pos_y = 500000
theta = 0.00000

[[dotbots]]
address = "AAAAAAAAAAAA0001"
calibrated = true
pos_x = 712132
pos_y = 712132
theta = 0.78540

[[dotbots]]
address = "AAAAAAAAAAAA0002"
calibrated = true
pos_x = 500000
pos_y = 800000
theta = 1.57080

[[dotbots]]
address = "AAAAAAAAAAAA0003"
calibrated = true
pos_x = 287867
pos_y = 712132
theta = 2.35619

[[dotbots]]
address = "AAAAAAAAAAAA0004"
calibrated = true
pos_x = 200000
pos_y = 500000
theta = 3.14159

[[dotbots]]
address = "AAAAAAAAAAAA0005"
calibrated = true
pos_x = 287867
pos_y = 287867
theta = 3.92699

[[dotbots]]
address = "AAAAAAAAAAAA0006"
calibrated = true
pos_x = 499999
pos_y = 200000
theta = 4.71239

[[dotbots]]
address = "AAAAAAAAAAAA0007"
calibrated = true
pos_x = 712132
pos_y = 287867
theta = 5.49779
