[[dotbots]]
address = "AAAAAAAAAAAA0000"
calibrated = true
pos_x = 800000
pos_y = 500000
theta = 4.71239

[[dotbots]]
address = "AAAAAAAAAAAA0001"
calibrated = true
pos_x = 799638
pos_y = 514720
theta = 4.76148

[[dotbots]]
address = "AAAAAAAAAAAA0002"
calibrated = true
pos_x = 798555
pos_y = 529405
theta = 4.81056

[[dotbots]]
address = "AAAAAAAAAAAA0003"
calibrated = true
pos_x = 796752
pos_y = 544019
theta = 4.85965

[[dotbots]]
address = "AAAAAAAAAAAA0004"
calibrated = true
pos_x = 794235
pos_y = 558527
theta = 4.90874

[[dotbots]]
address = "AAAAAAAAAAAA0005"
calibrated = true
pos_x = 791009
pos_y = 572894
theta = 4.95783

[[dotbots]]
address = "AAAAAAAAAAAA0006"
calibrated = true
pos_x = 787082
pos_y = 587085
theta = 5.00691

[[dotbots]]
address = "AAAAAAAAAAAA0007"
calibrated = true
pos_x = 782463
pos_y = 601066
theta = 5.05600

[[dotbots]]
address = "AAAAAAAAAAAA0008"
calibrated = true
pos_x = 777163
pos_y = 614805
theta = 5.10509

[[dotbots]]
address = "AAAAAAAAAAAA0009"
calibrated = true
pos_x = 771196
pos_y = 628266
theta = 5.15418

[[dotbots]]
address = "AAAAAAAAAAAA000A"
calibrated = true
pos_x = 764576
pos_y = 641419
theta = 5.20326

[[dotbots]]
address = "AAAAAAAAAAAA000B"
calibrated = true
pos_x = 757318
pos_y = 654230
theta = 5.25235

[[dotbots]]
address = "AAAAAAAAAAAA000C"
calibrated = true
pos_x = 749440
pos_y = 666671
theta = 5.30144

[[dotbots]]
address = "AAAAAAAAAAAA000D"
calibrated = true
pos_x = 740962
pos_y = 678709
theta = 5.35052

[[dotbots]]
address = "AAAAAAAAAAAA000E"
calibrated = true
pos_x = 731903
pos_y = 690317
theta = 5.39961

[[dotbots]]
address = "AAAAAAAAAAAA000F"
calibrated = true
pos_x = 722285
pos_y = 701467
theta = 5.44870

[[dotbots]]
address = "AAAAAAAAAAAA0010"
calibrated = true
pos_x = 712132
pos_y = 712132
theta = 5.49779

[[dotbots]]
address = "AAAAAAAAAAAA0011"
calibrated = true
pos_x = 701467
pos_y = 722285
theta = 5.54687

[[dotbots]]
address = "AAAAAAAAAAAA0012"
calibrated = true
pos_x = 690317
pos_y = 731903
theta = 5.59596

[[dotbots]]
address = "AAAAAAAAAAAA0013"
calibrated = true
pos_x = 678709
pos_y = 740962
theta = 5.64505

[[dotbots]]
address = "AAAAAAAAAAAA0014"
calibrated = true
pos_x = 666671
pos_y = 749440
theta = 5.69414

[[dotbots]]
address = "AAAAAAAAAAAA0015"
calibrated = true
pos_x = 654230
pos_y = 757318
theta = 5.74322

[[dotbots]]
address = "AAAAAAAAAAAA0016"
calibrated = true
pos_x = 641419
pos_y = 764576
theta = 5.79231

[[dotbots]]
address = "AAAAAAAAAAAA0017"
calibrated = true
pos_x = 628266
pos_y = 771196
theta = 5.84140

[[dotbots]]
address = "AAAAAAAAAAAA0018"
calibrated = true
pos_x = 614805
pos_y = 777163
theta = 5.89049

[[dotbots]]
address = "AAAAAAAAAAAA0019"
calibrated = true
pos_x = 601066
pos_y = 782463
theta = 5.93957

[[dotbots]]
address = "AAAAAAAAAAAA001A"
calibrated = true
pos_x = 587085
pos_y = 787082
theta = 5.98866

[[dotbots]]
address = "AAAAAAAAAAAA001B"
calibrated = true
pos_x = 572894
pos_y = 791009
theta = 6.03775

[[dotbots]]
address = "AAAAAAAAAAAA001C"
calibrated = true
pos_x = 558527
pos_y = 794235
theta = 6.08684

[[dotbots]]
address = "AAAAAAAAAAAA001D"
calibrated = true
pos_x = 544019
pos_y = 796752
theta = 6.13592

[[dotbots]]
address = "AAAAAAAAAAAA001E"
calibrated = true
pos_x = 529405
pos_y = 798555
theta = 6.18501

[[dotbots]]
address = "AAAAAAAAAAAA001F"
calibrated = true
pos_x = 514720
pos_y = 799638
theta = 6.23410

[[dotbots]]
address = "AAAAAAAAAAAA0020"
calibrated = true
pos_x = 500000
pos_y = 800000
theta = 0.00000

[[dotbots]]
address = "AAAAAAAAAAAA0021"
calibrated = true
pos_x = 485279
pos_y = 799638
theta = 0.04909

[[dotbots]]
address = "AAAAAAAAAAAA0022"
calibrated = true
pos_x = 470594
pos_y = 798555
theta = 0.09817

[[dotbots]]
address = "AAAAAAAAAAAA0023"
calibrated = true
pos_x = 455980
pos_y = 796752
theta = 0.14726

[[dotbots]]
address = "AAAAAAAAAAAA0024"
calibrated = true
pos_x = 441472
pos_y = 794235
theta = 0.19635

[[dotbots]]
address = "AAAAAAAAAAAA0025"
calibrated = true
pos_x = 427105
pos_y = 791009
theta = 0.24544

[[dotbots]]
address = "AAAAAAAAAAAA0026"
calibrated = true
pos_x = 412914
pos_y = 787082
theta = 0.29452

[[dotbots]]
address = "AAAAAAAAAAAA0027"
calibrated = true
pos_x = 398933
pos_y = 782463
theta = 0.34361

[[dotbots]]
address = "AAAAAAAAAAAA0028"
calibrated = true
pos_x = 385194
pos_y = 777163
theta = 0.39270

[[dotbots]]
address = "AAAAAAAAAAAA0029"
calibrated = true
pos_x = 371733
pos_y = 771196
theta = 0.44179

[[dotbots]]
address = "AAAAAAAAAAAA002A"
calibrated = true
pos_x = 358580
pos_y = 764576
theta = 0.49087

[[dotbots]]
address = "AAAAAAAAAAAA002B"
calibrated = true
pos_x = 345769
pos_y = 757318
theta = 0.53996

[[dotbots]]
address = "AAAAAAAAAAAA002C"
calibrated = true
pos_x = 333328
pos_y = 749440
theta = 0.58905

[[dotbots]]
address = "AAAAAAAAAAAA002D"
calibrated = true
pos_x = 321290
pos_y = 740962
theta = 0.63814

[[dotbots]]
address = "AAAAAAAAAAAA002E"
calibrated = true
pos_x = 309682
pos_y = 731903
theta = 0.68722

[[dotbots]]
address = "AAAAAAAAAAAA002F"
calibrated = true
pos_x = 298532
pos_y = 722285
theta = 0.73631

[[dotbots]]
address = "AAAAAAAAAAAA0030"
calibrated = true
pos_x = 287867
pos_y = 712132
theta = 0.78540

[[dotbots]]
address = "AAAAAAAAAAAA0031"
calibrated = true
pos_x = 277714
pos_y = 701467
theta = 0.83449

[[dotbots]]
address = "AAAAAAAAAAAA0032"
calibrated = true
pos_x = 268096
pos_y = 690317
theta = 0.88357

[[dotbots]]
address = "AAAAAAAAAAAA0033"
calibrated = true
pos_x = 259037
pos_y = 678709
theta = 0.93266

[[dotbots]]
address = "AAAAAAAAAAAA0034"
calibrated = true
pos_x = 250559
pos_y = 666671
theta = 0.98175

[[dotbots]]
address = "AAAAAAAAAAAA0035"
calibrated = true
pos_x = 242681
pos_y = 654230
theta = 1.03084

[[dotbots]]
address = "AAAAAAAAAAAA0036"
calibrated = true
pos_x = 235423
pos_y = 641419
theta = 1.07992

[[dotbots]]
address = "AAAAAAAAAAAA0037"
calibrated = true
pos_x = 228803
pos_y = 628266
theta = 1.12901

[[dotbots]]
address = "AAAAAAAAAAAA0038"
calibrated = true
pos_x = 222836
pos_y = 614805
theta = 1.17810

[[dotbots]]
address = "AAAAAAAAAAAA0039"
calibrated = true
pos_x = 217536
pos_y = 601066
theta = 1.22718

[[dotbots]]
address = "AAAAAAAAAAAA003A"
calibrated = true
pos_x = 212917
pos_y = 587085
theta = 1.27627

[[dotbots]]
address = "AAAAAAAAAAAA003B"
calibrated = true
pos_x = 208990
pos_y = 572894
theta = 1.32536

[[dotbots]]
address = "AAAAAAAAAAAA003C"
calibrated = true
pos_x = 205764
pos_y = 558527
theta = 1.37445

[[dotbots]]
address = "AAAAAAAAAAAA003D"
calibrated = true
pos_x = 203247
pos_y = 544019
theta = 1.42353

[[dotbots]]
address = "AAAAAAAAAAAA003E"
calibrated = true
pos_x = 201444
pos_y = 529405
theta = 1.47262

[[dotbots]]
address = "AAAAAAAAAAAA003F"
calibrated = true
pos_x = 200361
pos_y = 514720
theta = 1.52171

[[dotbots]]
address = "AAAAAAAAAAAA0040"
calibrated = true
pos_x = 200000
pos_y = 500000
theta = 1.57080

[[dotbots]]
address = "AAAAAAAAAAAA0041"
calibrated = true
pos_x = 200361
pos_y = 485279
theta = 1.61988

[[dotbots]]
address = "AAAAAAAAAAAA0042"
calibrated = true
pos_x = 201444
pos_y = 470594
theta = 1.66897

[[dotbots]]
address = "AAAAAAAAAAAA0043"
calibrated = true
pos_x = 203247
pos_y = 455980
theta = 1.71806

[[dotbots]]
address = "AAAAAAAAAAAA0044"
calibrated = true
pos_x = 205764
pos_y = 441472
theta = 1.76715

[[dotbots]]
address = "AAAAAAAAAAAA0045"
calibrated = true
pos_x = 208990
pos_y = 427105
theta = 1.81623

[[dotbots]]
address = "AAAAAAAAAAAA0046"
calibrated = true
pos_x = 212917
pos_y = 412914
theta = 1.86532

[[dotbots]]
address = "AAAAAAAAAAAA0047"
calibrated = true
pos_x = 217536
pos_y = 398933
theta = 1.91441

[[dotbots]]
address = "AAAAAAAAAAAA0048"
calibrated = true
pos_x = 222836
pos_y = 385194
theta = 1.96350

[[dotbots]]
address = "AAAAAAAAAAAA0049"
calibrated = true
pos_x = 228803
pos_y = 371733
theta = 2.01258

[[dotbots]]
address = "AAAAAAAAAAAA004A"
calibrated = true
pos_x = 235423
pos_y = 358580
theta = 2.06167

[[dotbots]]
address = "AAAAAAAAAAAA004B"
calibrated = true
pos_x = 242681
pos_y = 345769
theta = 2.11076

[[dotbots]]
address = "AAAAAAAAAAAA004C"
calibrated = true
pos_x = 250559
pos_y = 333328
theta = 2.15984

[[dotbots]]
address = "AAAAAAAAAAAA004D"
calibrated = true
pos_x = 259037
pos_y = 321290
theta = 2.20893

[[dotbots]]
address = "AAAAAAAAAAAA004E"
calibrated = true
pos_x = 268096
pos_y = 309682
theta = 2.25802

[[dotbots]]
address = "AAAAAAAAAAAA004F"
calibrated = true
pos_x = 277714
pos_y = 298532
theta = 2.30711

[[dotbots]]
address = "AAAAAAAAAAAA0050"
calibrated = true
pos_x = 287867
pos_y = 287867
theta = 2.35619

[[dotbots]]
address = "AAAAAAAAAAAA0051"
calibrated = true
pos_x = 298532
pos_y = 277714
theta = 2.40528

[[dotbots]]
address = "AAAAAAAAAAAA0052"
calibrated = true
pos_x = 309682
pos_y = 268096
theta = 2.45437

[[dotbots]]
address = "AAAAAAAAAAAA0053"
calibrated = true
pos_x = 321290
pos_y = 259037
theta = 2.50346

[[dotbots]]
address = "AAAAAAAAAAAA0054"
calibrated = true
pos_x = 333328
pos_y = 250559
theta = 2.55254

[[dotbots]]
address = "AAAAAAAAAAAA0055"
calibrated = true
pos_x = 345769
pos_y = 242681
theta = 2.60163

[[dotbots]]
address = "AAAAAAAAAAAA0056"
calibrated = true
pos_x = 358580
pos_y = 235423
theta = 2.65072

[[dotbots]]
address = "AAAAAAAAAAAA0057"
calibrated = true
pos_x = 371733
pos_y = 228803
theta = 2.69981

[[dotbots]]
address = "AAAAAAAAAAAA0058"
calibrated = true
pos_x = 385194
pos_y = 222836
theta = 2.74889

[[dotbots]]
address = "AAAAAAAAAAAA0059"
calibrated = true
pos_x = 398933
pos_y = 217536
theta = 2.79798

[[dotbots]]
address = "AAAAAAAAAAAA005A"
calibrated = true
pos_x = 412914
pos_y = 212917
theta = 2.84707

[[dotbots]]
address = "AAAAAAAAAAAA005B"
calibrated = true
pos_x = 427105
pos_y = 208990
theta = 2.89616

[[dotbots]]
address = "AAAAAAAAAAAA005C"
calibrated = true
pos_x = 441472
pos_y = 205764
theta = 2.94524

[[dotbots]]
address = "AAAAAAAAAAAA005D"
calibrated = true
pos_x = 455980
pos_y = 203247
theta = 2.99433

[[dotbots]]
address = "AAAAAAAAAAAA005E"
calibrated = true
pos_x = 470594
pos_y = 201444
theta = 3.04342

[[dotbots]]
address = "AAAAAAAAAAAA005F"
calibrated = true
pos_x = 485279
pos_y = 200361
theta = 3.09251

[[dotbots]]
address = "AAAAAAAAAAAA0060"
calibrated = true
pos_x = 499999
pos_y = 200000
theta = 3.14159

[[dotbots]]
address = "AAAAAAAAAAAA0061"
calibrated = true
pos_x = 514720
pos_y = 200361
theta = 3.19068

[[dotbots]]
address = "AAAAAAAAAAAA0062"
calibrated = true
pos_x = 529405
pos_y = 201444
theta = 3.23977

[[dotbots]]
address = "AAAAAAAAAAAA0063"
calibrated = true
pos_x = 544019
pos_y = 203247
theta = 3.28885

[[dotbots]]
address = "AAAAAAAAAAAA0064"
calibrated = true
pos_x = 558527
pos_y = 205764
theta = 3.33794

[[dotbots]]
address = "AAAAAAAAAAAA0065"
calibrated = true
pos_x = 572894
pos_y = 208990
theta = 3.38703

[[dotbots]]
address = "AAAAAAAAAAAA0066"
calibrated = true
pos_x = 587085
pos_y = 212917
theta = 3.43612

[[dotbots]]
address = "AAAAAAAAAAAA0067"
calibrated = true
pos_x = 601066
pos_y = 217536
theta = 3.48520

[[dotbots]]
address = "AAAAAAAAAAAA0068"
calibrated = true
pos_x = 614805
pos_y = 222836
theta = 3.53429

[[dotbots]]
address = "AAAAAAAAAAAA0069"
calibrated = true
pos_x = 628266
pos_y = 228803
theta = 3.58338

[[dotbots]]
address = "AAAAAAAAAAAA006A"
calibrated = true
pos_x = 641419
pos_y = 235423
theta = 3.63247

[[dotbots]]
address = "AAAAAAAAAAAA006B"
calibrated = true
pos_x = 654230
pos_y = 242681
theta = 3.68155

[[dotbots]]
address = "AAAAAAAAAAAA006C"
calibrated = true
pos_x = 666671
pos_y = 250559
theta = 3.73064

[[dotbots]]
address = "AAAAAAAAAAAA006D"
calibrated = true
pos_x = 678709
pos_y = 259037
theta = 3.77973

[[dotbots]]
address = "AAAAAAAAAAAA006E"
calibrated = true
pos_x = 690317
pos_y = 268096
theta = 3.82882

[[dotbots]]
address = "AAAAAAAAAAAA006F"
calibrated = true
pos_x = 701467
pos_y = 277714
theta = 3.87790

[[dotbots]]
address = "AAAAAAAAAAAA0070"
calibrated = true
pos_x = 712132
pos_y = 287867
theta = 3.92699

[[dotbots]]
address = "AAAAAAAAAAAA0071"
calibrated = true
pos_x = 722285
pos_y = 298532
theta = 3.97608

[[dotbots]]
address = "AAAAAAAAAAAA0072"
calibrated = true
pos_x = 731903
pos_y = 309682
theta = 4.02517

[[dotbots]]
address = "AAAAAAAAAAAA0073"
calibrated = true
pos_x = 740962
pos_y = 321290
theta = 4.07425

[[dotbots]]
address = "AAAAAAAAAAAA0074"
calibrated = true
pos_x = 749440
pos_y = 333328
theta = 4.12334

[[dotbots]]
address = "AAAAAAAAAAAA0075"
calibrated = true
pos_x = 757318
pos_y = 345769
theta = 4.17243

[[dotbots]]
address = "AAAAAAAAAAAA0076"
calibrated = true
pos_x = 764576
pos_y = 358580
theta = 4.22152

[[dotbots]]
address = "AAAAAAAAAAAA0077"
calibrated = true
pos_x = 771196
pos_y = 371733
theta = 4.27060

[[dotbots]]
address = "AAAAAAAAAAAA0078"
calibrated = true
pos_x = 777163
pos_y = 385194
theta = 4.31969

[[dotbots]]
address = "AAAAAAAAAAAA0079"
calibrated = true
pos_x = 782463
pos_y = 398933
theta = 4.36878

[[dotbots]]
address = "AAAAAAAAAAAA007A"
calibrated = true
pos_x = 787082
pos_y = 412914
theta = 4.41786

[[dotbots]]
address = "AAAAAAAAAAAA007B"
calibrated = true
pos_x = 791009
pos_y = 427105
theta = 4.46695

[[dotbots]]
address = "AAAAAAAAAAAA007C"
calibrated = true
pos_x = 794235
pos_y = 441472
theta = 4.51604

[[dotbots]]
address = "AAAAAAAAAAAA007D"
calibrated = true
pos_x = 796752
pos_y = 455980
theta = 4.56513

[[dotbots]]
address = "AAAAAAAAAAAA007E"
calibrated = true
pos_x = 798555
pos_y = 470594
theta = 4.61421

[[dotbots]]
address = "AAAAAAAAAAAA007F"
calibrated = true
pos_x = 799638
pos_y = 485279
theta = 4.66330
