[[dotbots]]
address = "09657144DD0810EC"
calibrated = true
pos_x = 24994
pos_y = 224191
theta = 0.74489

[[dotbots]]
address = "63003E6A572C7FFA"
calibrated = true
pos_x = 239074
pos_y = 432388
theta = 3.12495

[[dotbots]]
address = "B449BB046234AC54"
calibrated = true
pos_x = 534716
pos_y = 57092
theta = 2.06418

[[dotbots]]
address = "55DF570AF68C8CED"
calibrated = true
pos_x = 663115
pos_y = 548432
theta = 1.74486

[[dotbots]]
address = "47BD200F43AFD7CE"
calibrated = true
pos_x = 664489
pos_y = 343414
theta = 2.99737

[[dotbots]]
address = "5846FCD737074402"
calibrated = true
pos_x = 358686
pos_y = 356836
theta = 2.28566

[[dotbots]]
address = "739B789D8BE1E55A"
calibrated = true
pos_x = 750092
pos_y = 168560
theta = 0.25672

[[dotbots]]
address = "782C89D7D706EE5F"
calibrated = true
pos_x = 674352
pos_y = 858971
theta = 0.8823

[[dotbots]]
address = "FA8B6FC70AA442FE"
calibrated = true
pos_x = 295840
pos_y = 399199
theta = 2.63127

[[dotbots]]
address = "C7F6DF9EA89B5841"
calibrated = true
pos_x = 294684
pos_y = 864246
theta = 1.9102

[[dotbots]]
address = "0496B3F3A85A3BFF"
calibrated = true
pos_x = 717419
pos_y = 272438
theta = 0.92441

[[dotbots]]
address = "D5909ABEDC85A40F"
calibrated = true
pos_x = 293784
pos_y = 36593
theta = 0.47605

[[dotbots]]
address = "0D94C9412F9F8B85"
calibrated = true
pos_x = 888263
pos_y = 965157
theta = 0.27058

[[dotbots]]
address = "FCB88E34E32EE5C0"
calibrated = true
pos_x = 49089
pos_y = 183307
theta = 0.94451

[[dotbots]]
address = "83DFCE33C47334A0"
calibrated = true
pos_x = 159908
pos_y = 966008
theta = 1.05086

[[dotbots]]
address = "176D902807D73FD8"
calibrated = true
pos_x = 325571
pos_y = 503255
theta = 2.32959

[[dotbots]]
address = "93FB4E1D1E6D7EB6"
calibrated = true
pos_x = 868265
pos_y = 798644
theta = 1.00663

[[dotbots]]
address = "DA818E6513D09531"
calibrated = true
pos_x = 806405
pos_y = 230702
theta = 0.09026

[[dotbots]]
address = "6940AC1FD5C352B6"
calibrated = true
pos_x = 609952
pos_y = 565124
theta = 0.09229

[[dotbots]]
address = "FB387E59B09BA79F"
calibrated = true
pos_x = 769605
pos_y = 194972
theta = 2.43432

[[dotbots]]
address = "D981C7A2961BA426"
calibrated = true
pos_x = 223023
pos_y = 612445
theta = 2.54499

[[dotbots]]
address = "0FAE9D4285619366"
calibrated = true
pos_x = 838777
pos_y = 629334
theta = 1.23499

[[dotbots]]
address = "8A767401A4D6FF91"
calibrated = true
pos_x = 87285
pos_y = 5892
theta = 1.21685

[[dotbots]]
address = "7282EEE1C5542205"
calibrated = true
pos_x = 802799
pos_y = 334081
theta = 1.72349

[[dotbots]]
address = "13A98F30DA34688B"
calibrated = true
pos_x = 513305
pos_y = 698951
theta = 2.80166

[[dotbots]]
address = "33F88210FDF4DE15"
calibrated = true
pos_x = 988130
pos_y = 396451
theta = 0.7393

[[dotbots]]
address = "C619EA196EC9AB31"
calibrated = true
pos_x = 17686
pos_y = 593734
theta = 2.52245

[[dotbots]]
address = "78908E0E13D7DD0E"
calibrated = true
pos_x = 806062
pos_y = 818762
theta = 1.59109

[[dotbots]]
address = "A138FAC9EF7DD136"
calibrated = true
pos_x = 976811
pos_y = 464532
theta = 2.99959

[[dotbots]]
address = "8B76C69FA9C60E3B"
calibrated = true
pos_x = 51555
pos_y = 663151
theta = 2.50309

[[dotbots]]
address = "8DD952FA9237E1B8"
calibrated = true
pos_x = 853167
pos_y = 749006
theta = 0.80222

[[dotbots]]
address = "2FF4ADF785E8A7DE"
calibrated = true
pos_x = 271154
pos_y = 45927
theta = 2.43728

[[dotbots]]
address = "7CE3B4FFF9134F51"
calibrated = true
pos_x = 60839
pos_y = 793826
theta = 1.66371

[[dotbots]]
address = "E0635ACA1D6AC0C6"
calibrated = true
pos_x = 369863
pos_y = 44548
theta = 0.46689

[[dotbots]]
address = "7A7CE5175B7C7966"
calibrated = true
pos_x = 284406
pos_y = 715527
theta = 2.09891

[[dotbots]]
address = "702DDBAB57694930"
calibrated = true
pos_x = 982125
pos_y = 5205
theta = 0.05286

[[dotbots]]
address = "F5C47926AC816792"
calibrated = true
pos_x = 781339
pos_y = 157353
theta = 0.21181

[[dotbots]]
address = "BAF4DAEDD20C2C56"
calibrated = true
pos_x = 742535
pos_y = 701745
theta = 2.54157

[[dotbots]]
address = "16BF6EE52898271E"
calibrated = true
pos_x = 531284
pos_y = 370401
theta = 0.38407

[[dotbots]]
address = "4E467C6E713A2B84"
calibrated = true
pos_x = 508615
pos_y = 63066
theta = 0.72575

[[dotbots]]
address = "BEAEC05DFBA5A9E5"
calibrated = true
pos_x = 88237
pos_y = 687434
theta = 0.56141

[[dotbots]]
address = "76B293F0AC3A9D54"
calibrated = true
pos_x = 510386
pos_y = 598459
theta = 1.51232

[[dotbots]]
address = "29090EF304663286"
calibrated = true
pos_x = 138281
pos_y = 747205
theta = 1.77579

[[dotbots]]
address = "779C9F282F2FF33F"
calibrated = true
pos_x = 972623
pos_y = 917089
theta = 1.17561

[[dotbots]]
address = "668ECE79457C34F5"
calibrated = true
pos_x = 422783
pos_y = 454957
theta = 1.0789

[[dotbots]]
address = "F9609AFE0F175920"
calibrated = true
pos_x = 915588
pos_y = 818034
theta = 1.70337

[[dotbots]]
address = "8E100D5CE5974C4F"
calibrated = true
pos_x = 821268
pos_y = 56121
theta = 0.97233

[[dotbots]]
address = "A8EC3A9D70226366"
calibrated = true
pos_x = 188677
pos_y = 539357
theta = 0.51591

[[dotbots]]
address = "AA93326B7FDFFE72"
calibrated = true
pos_x = 739363
pos_y = 386058
theta = 2.23777

[[dotbots]]
address = "703A04B62565B0FC"
calibrated = true
pos_x = 208038
pos_y = 316026
theta = 0.15317

[[dotbots]]
address = "6D1D9FB7320A5547"
calibrated = true
pos_x = 420849
pos_y = 939219
theta = 3.03772

[[dotbots]]
address = "40BF860B6B90E309"
calibrated = true
pos_x = 453469
pos_y = 255412
theta = 0.07609

[[dotbots]]
address = "CC4E691A41659AD8"
calibrated = true
pos_x = 964913
pos_y = 827687
theta = 2.49927

[[dotbots]]
address = "FFAA1E7C97564157"
calibrated = true
pos_x = 984189
pos_y = 755316
theta = 2.32703

[[dotbots]]
address = "238155FA60B0AEAE"
calibrated = true
pos_x = 681017
pos_y = 218219
theta = 1.14973

[[dotbots]]
address = "AB3ACB854BB0AB25"
calibrated = true
pos_x = 529467
pos_y = 361193
theta = 1.24428

[[dotbots]]
address = "75034772252D2D4C"
calibrated = true
pos_x = 912115
pos_y = 43456
theta = 0.1081

[[dotbots]]
address = "0153F99087332C59"
calibrated = true
pos_x = 148699
pos_y = 537718
theta = 1.10996

[[dotbots]]
address = "A2B38E6481DD8CDF"
calibrated = true
pos_x = 619276
pos_y = 180470
theta = 0.99667

[[dotbots]]
address = "559EE34AD5A9360F"
calibrated = true
pos_x = 375442
pos_y = 427091
theta = 2.03698

[[dotbots]]
address = "39E2801C0AE8B971"
calibrated = true
pos_x = 773174
pos_y = 94149
theta = 0.56837

[[dotbots]]
address = "1D7395739DF1E8D8"
calibrated = true
pos_x = 776390
pos_y = 470305
theta = 1.85677

[[dotbots]]
address = "311A3DAE4B3E99FE"
calibrated = true
pos_x = 926459
pos_y = 195199
theta = 2.61217

[[dotbots]]
address = "74B68A04C097144E"
calibrated = true
pos_x = 781070
pos_y = 103079
theta = 0.86931

[[dotbots]]
address = "FB56F116D1744CF8"
calibrated = true
pos_x = 279021
pos_y = 830726
theta = 2.35482

[[dotbots]]
address = "1B54B79BCF9BEAC7"
calibrated = true
pos_x = 461710
pos_y = 523145
theta = 0.31662

[[dotbots]]
address = "73700AAB7749C998"
calibrated = true
pos_x = 152621
pos_y = 903279
theta = 0.12796

[[dotbots]]
address = "4F0D5C5B86964845"
calibrated = true
pos_x = 159422
pos_y = 213267
theta = 1.8158

[[dotbots]]
address = "9E2EC8A33427F788"
calibrated = true
pos_x = 893428
pos_y = 889091
theta = 1.55573

[[dotbots]]
address = "18ED4400F5489CE4"
calibrated = true
pos_x = 461507
pos_y = 600840
theta = 1.09039

[[dotbots]]
address = "1D753394048A0490"
calibrated = true
pos_x = 883755
pos_y = 147159
theta = 2.70515

[[dotbots]]
address = "32E64F3744EB71E2"
calibrated = true
pos_x = 670461
pos_y = 403055
theta = 0.12871

[[dotbots]]
address = "2AEF8F23AD3E056C"
calibrated = true
pos_x = 156094
pos_y = 234389
theta = 0.00257

[[dotbots]]
address = "FE4F98C99EE3C7C1"
calibrated = true
pos_x = 42098
pos_y = 470936
theta = 2.76915

[[dotbots]]
address = "916C7AC487D5BDEB"
calibrated = true
pos_x = 279185
pos_y = 720350
theta = 1.089

[[dotbots]]
address = "4B201D688DAF04DD"
calibrated = true
pos_x = 911975
pos_y = 158474
theta = 1.01504

[[dotbots]]
address = "E5C1D034CDC32CAC"
calibrated = true
pos_x = 618061
pos_y = 463883
theta = 0.04954

[[dotbots]]
address = "F08A8818273F2412"
calibrated = true
pos_x = 75117
pos_y = 744457
theta = 1.98279

[[dotbots]]
address = "8236236FF19D4A6C"
calibrated = true
pos_x = 856422
pos_y = 132337
theta = 2.996

[[dotbots]]
address = "3FD94AFE113E39DB"
calibrated = true
pos_x = 558867
pos_y = 400633
theta = 2.57603

[[dotbots]]
address = "83CD65F7CF462C0B"
calibrated = true
pos_x = 491050
pos_y = 273514
theta = 2.21125

[[dotbots]]
address = "EC9C2C7C427350ED"
calibrated = true
pos_x = 919435
pos_y = 8513
theta = 0.75566

[[dotbots]]
address = "F13E9405C1B344CE"
calibrated = true
pos_x = 502842
pos_y = 141221
theta = 1.80566

[[dotbots]]
address = "7FDCCED9D9A59BEE"
calibrated = true
pos_x = 610851
pos_y = 423479
theta = 1.27054

[[dotbots]]
address = "2C56C7AD409F85C1"
calibrated = true
pos_x = 23215
pos_y = 615319
theta = 1.59674

[[dotbots]]
address = "A76B08F13CEE9362"
calibrated = true
pos_x = 394653
pos_y = 593132
theta = 2.2277

[[dotbots]]
address = "917411A8928CEFB3"
calibrated = true
pos_x = 642301
pos_y = 867234
theta = 0.47815

[[dotbots]]
address = "366FF2E0D1B38152"
calibrated = true
pos_x = 383084
pos_y = 438777
theta = 2.045

[[dotbots]]
address = "33B22CFE33612EE8"
calibrated = true
pos_x = 758139
pos_y = 622479
theta = 1.72578

[[dotbots]]
address = "F9646508F1290E0A"
calibrated = true
pos_x = 856678
pos_y = 643034
theta = 0.95848

[[dotbots]]
address = "9EAD38250E2789F7"
calibrated = true
pos_x = 294990
pos_y = 568932
theta = 1.09007

[[dotbots]]
address = "FDCD62E8D351BBB5"
calibrated = true
pos_x = 389569
pos_y = 411081
theta = 0.21263

[[dotbots]]
address = "D711E24EEED1A806"
calibrated = true
pos_x = 651128
pos_y = 570825
theta = 2.31102

[[dotbots]]
address = "325218BA13F86694"
calibrated = true
pos_x = 840346
pos_y = 566031
theta = 0.1798

[[dotbots]]
address = "85623B868486AEC1"
calibrated = true
pos_x = 228001
pos_y = 462212
theta = 2.7316

[[dotbots]]
address = "6DE935DA274E5D90"
calibrated = true
pos_x = 506092
pos_y = 642343
theta = 2.46139

[[dotbots]]
address = "75219943E337D9EE"
calibrated = true
pos_x = 947336
pos_y = 422271
theta = 1.37423

[[dotbots]]
address = "D3112D82C2A3032A"
calibrated = true
pos_x = 135151
pos_y = 147961
theta = 2.6146

[[dotbots]]
address = "33DAB702E4FB07EA"
calibrated = true
pos_x = 986401
pos_y = 784934
theta = 0.06403

[[dotbots]]
address = "4B5D043302B6B04A"
calibrated = true
pos_x = 259972
pos_y = 226301
theta = 1.4608
