[[dotbots]]
address = "aaaaaaaaaaaa0000"
calibrated = true
pos_x = 50000
pos_y = 50000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0001"
calibrated = true
pos_x = 500000
pos_y = 50000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0002"
calibrated = true
pos_x = 950000
pos_y = 50000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0003"
calibrated = true
pos_x = 50000
pos_y = 500000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0004"
calibrated = true
pos_x = 500000
pos_y = 500000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0005"
calibrated = true
pos_x = 950000
pos_y = 500000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0006"
calibrated = true
pos_x = 50000
pos_y = 950000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0007"
calibrated = true
pos_x = 500000
pos_y = 950000
theta = 0.0

[[dotbots]]
address = "AAAAAAAAAAAA0008"
calibrated = true
pos_x = 950000
pos_y = 950000
theta = 0.0
